### ISSUE TITLE
Flip  option bnot working.  

### ISSUE THREAD

**Issue by suww37** [MiSTer-devel/Arcade-Athena_MiSTer#1]
In crt monitor, the screen of Athena game is upside down. The Flip option  is not working , so please support it. Thank you

**Comment by misteraddons** [comment]
I can confirm. The video is flipped by default (upside-down) and the flip option doesn't result in a visible picture.

**Comment by RndMnkIII** [comment]
The video is not flipped by default,  this game displays this way.  As provissional solution try enable flip,  save the settings and then load the core again. The latter would have to repeat up to two more times for the image to be displayed correctly. Sorry, I'm looking for a solution to this.

**Comment by RndMnkIII** [comment]
https://twitter.com/RndMnkIII/status/1534835630110347264?s=20&t=O-rvCKiU55MsgL08WRF12g
The procedure to solve this is explained.

**Comment by suww37** [comment]
Even with the video on Twitter, I couldn't solve the screen flipped. Perhaps the method you did does not seem to be applicable to the 15khz crt screen
